### PR TITLE
New documentation

### PR DESCRIPTION
**Pull request by AdrianDampc**
Pull request for issue: #

Are there more related issue(s): # #

Component Screenshot:

Description (short):

### CODE REVIEW

**Comment by fokusferit** [comment]
@AdrianDampc any update here ? Looks like you have to merge master first and push it back to your branch.

**Comment by AdrianDampc** [comment]
@fokusferit Hope it is solved

**Comment by fragsalat** [comment]
There are still merge conflicts

**Comment by AdrianDampc** [comment]
@fragsalat  damn, I removed them, I believe I can't do it properly... I will ask you next week to help me with that.

**Comment by fokusferit** [comment]
@AdrianDampc when you have time, let's try to fix this today ?

**Comment by AdrianDampc** [comment]
@fokusferit  sure

**Comment by fokusferit** [comment]
Closing in favor of #138

**Pull request closed without merging**
